### ISSUE TITLE
light color theme?

### ISSUE THREAD

**Issue by propertone** [evilsocket/uroboros#7]
The uro output is hard to read if you have a white background in the terminal. Would it be possible to provide a different color theme option (or auto-detect it) that works on a light background? And thanks for this great tool!

**Comment by evilsocket** [comment]
i started looking into this and while the package we use for UI does have some support for themes ( https://github.com/gizak/termui/blob/master/theme.go ), it seems that hardcodes lots of color and style values anyway (just search for "ColorWhite" in this file https://github.com/gizak/termui/blob/master/widgets/plot.go for instance) making themes pretty much pointless in solving the issue that you are experiencing ... i apologize but at this time i think it'll just be easier if you could use a darker terminal profile :/
